output_dir: "./results"

data:
  train: "./data/train"
  test: "./data/test"

model:
  in_channels: 3
  num_classes: 5
  embed_dim: 256
  num_heads: 4
  num_layers: 2

training:
  epochs: 50
  batch_size: 8
  lr: 1e-4
  device: "cuda"
  save_freq: 10

inference:
  checkpoint: "./results/checkpoint_epoch50.pth"
  device: "cuda"
  output_dir: "./results/predictions"